# Generated by Django 5.2.8 on 2025-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('secretary', 'Secretary'), ('dentist', 'Dentist')], max_length=25, null=True, verbose_name='User Role'),
        ),
    ]
