# Generated by Django 5.2.8 on 2026-02-07 00:08

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAIL', 'Login Failed'), ('PASSWORD_RESET_REQUEST', 'Password Reset Requested'), ('PASSWORD_CHANGE', 'Password Changed'), ('PERMISSIONS_CHANGED', 'Permissions Changed'), ('LOGOUT', 'Logout')], max_length=64)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_event',
            },
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Ghana number in +233XXXXXXXXX format.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: +233XXXXXXXXX (9 digits after +233).', regex='^\\+233\\d{9}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('secretary', 'Secretary'), ('dentist', 'Dentist')], help_text='Business role (required for non-superusers).', max_length=25, null=True, verbose_name='User Role'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_role'], name='custom_user_user_ro_ab0b05_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'user_role'], name='custom_user_is_acti_5853f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', True), ('user_role__isnull', False), _connector='OR'), name='role_required_unless_superuser'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', False), ('user_role__isnull', True), _connector='OR'), name='superuser_role_must_be_null'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', 'created_at'], name='audit_event_action_2cae66_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='audit_event_actor_i_032040_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_user', 'created_at'], name='audit_event_target__de50f4_idx'),
        ),
    ]
