# Generated by Django 5.2.8 on 2026-02-07 00:08

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFolderCounter',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'patient_folder_counter',
            },
        ),
        migrations.CreateModel(
            name='AcquisitionChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'acquisition_channel',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='acquisition_is_acti_20b0a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Stable system code e.g. GENERAL, VIP, ORTHO. (Seed GENERAL as default)', unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'patient_type',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='patient_typ_is_acti_3d060b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_number', models.CharField(db_index=True, editable=False, help_text='Immutable patient folder number e.g. DEN-2026-001', max_length=20, unique=True)),
                ('profile_picture_url', models.URLField(blank=True, help_text="URL to the patient's profile avatar (optional).", max_length=255, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone_number', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: +233XXXXXXXXX (9 digits after +233).', regex='^\\+233\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('is_child', models.BooleanField(db_index=True, default=False)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: +233XXXXXXXXX (9 digits after +233).', regex='^\\+233\\d{9}$')])),
                ('guardian_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_address', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('acquisition_channel', models.ForeignKey(help_text='Acquisition channel (defaults to WALK_IN if omitted).', on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.acquisitionchannel')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this patient record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_patients', to=settings.AUTH_USER_MODEL)),
                ('patient_type', models.ForeignKey(help_text='Dynamic patient category (defaults to GENERAL if omitted).', on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.patienttype')),
            ],
            options={
                'db_table': 'patient',
                'ordering': ['last_name', 'first_name'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientImportExportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('file_format', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel (XLSX)')], max_length=10)),
                ('source_file', models.CharField(blank=True, max_length=500, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('result_file', models.CharField(blank=True, max_length=500, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('row_errors', models.JSONField(default=list, help_text='[{row: int, errors: {...}}]')),
                ('options', models.JSONField(default=dict, help_text='Job config: skip_duplicates, update_existing, etc.')),
                ('export_filters', models.JSONField(default=dict, help_text='Filters applied during export.')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_import_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_import_export_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', 'status'], name='patient_imp_job_typ_734368_idx'), models.Index(fields=['initiated_by', 'created_at'], name='patient_imp_initiat_5e8834_idx'), models.Index(fields=['status', 'created_at'], name='patient_imp_status_c8dda4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientMergeHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secondary_patient_id', models.UUIDField(help_text='UUID of the patient that was merged (may be deleted).')),
                ('secondary_folder_number', models.CharField(help_text='Folder number of the merged patient (for reference).', max_length=20)),
                ('secondary_patient_snapshot', models.JSONField(help_text='Snapshot of the secondary patient data at time of merge.')),
                ('merge_reason', models.TextField(blank=True, default='', help_text='Optional reason for the merge.')),
                ('fields_updated', models.JSONField(default=list, help_text='List of fields updated on the primary patient.')),
                ('related_records_transferred', models.JSONField(default=dict, help_text='Summary of related records transferred.')),
                ('merged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_merges_performed', to=settings.AUTH_USER_MODEL)),
                ('primary_patient', models.ForeignKey(help_text='The patient record that was kept.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_history_as_primary', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_merge_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['primary_patient', 'created_at'], name='patient_mer_primary_e73f32_idx'), models.Index(fields=['secondary_patient_id'], name='patient_mer_seconda_8d58d8_idx'), models.Index(fields=['merged_by', 'created_at'], name='patient_mer_merged__1186fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientReferral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referrer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='patients.patient')),
                ('referrer_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_patients', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_referral',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('referrer_patient__isnull', False), ('referrer_name__isnull', True)), models.Q(('referrer_patient__isnull', True), ('referrer_name__isnull', False)), _connector='OR'), name='exactly_one_referrer_source')],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patient_last_na_abf268_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='patient_phone_n_39669a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_child', 'last_name'], name='patient_is_chil_6603e9_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_type'], name='patient_patient_4b1ead_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['acquisition_channel'], name='patient_acquisi_0b65cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('is_child', False), models.Q(('guardian_name__isnull', False), ('guardian_phone__isnull', False)), _connector='OR'), name='guardian_required_if_child'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('is_child', True), models.Q(('guardian_name__isnull', True), ('guardian_phone__isnull', True), ('guardian_occupation__isnull', True), ('guardian_address__isnull', True), ('guardian_email__isnull', True)), _connector='OR'), name='guardian_must_be_null_if_not_child'),
        ),
    ]
